//Database Schema Reference
const RestroomSchema = {
    StarbucksId: String,
    Name: String,
    BrandName: String,
    StoreNumber: String,
    PhoneNumber: String,
    OwnershipType: String,
    Street1: String,
    Street2: String,
    Street3: String,
    City: String,
    CountrySubdivisionCode: String,
    CountryCode: String,
    PostalCode: String,
    Longitude: Number,
    Latitude: Number,
    TimezoneOffset: Number,
    TimezoneId: String,
    TimezoneOlsonId: String,
    FirstSeen: String,
    LastSeen: String,
    Downvotes: Number,
    Flagged: Boolean,
    Upvotes: Number,
};
